version: "2"
services:
    mysql:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=symfony
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
    php:
        build:
            context: docker/php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
          - mysql
    nginx:
        build: docker/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        links:
          - php
          - mysql
