version: "2"
services:
    db:
      image: mysql
      ports:
          - "127.0.0.1:3306:3306"
      volumes:
          - "./.data/db:/var/lib/mysql"
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=symfony
          - MYSQL_USER=root
          - MYSQL_PASSWORD=root
    php:
        build:
            context: docker/php-fpm
        ports:
            - "127.0.0.1:9000:9000"
        volumes:
            - ./:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - db
    nginx:
        build: docker/nginx
        ports:
            - "127.0.0.1:80:80"
            - "443:443"
        volumes_from:
            - php
        volumes:
            - ./:/var/www/symfony
            - ./logs/nginx/:/var/log/nginx