# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        WarehouseBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: WarehouseBundle:User
                property: name
    access_control:
            - { path: ^/home, roles: ROLE_USER }
            - { path: ^/category, roles: ROLE_USER }
            - { path: ^/product, roles: ROLE_USER }
            - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            provider: our_db_provider

            logout:
                path:   /logout
                target: /

