<?php

namespace WarehouseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getAllCategories ()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('c')
            ->from('WarehouseBundle:Category', 'c')
            ->orderBy('c.id', 'ASC');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
