<?php

namespace WarehouseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getAllProducts ()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('p')
            ->from('WarehouseBundle:Product', 'p')
            ->orderBy('p.id', 'ASC');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
