<?php

namespace WarehouseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllUsers()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('u')
            ->from('WarehouseBundle:User', 'u')
            ->orderBy('u.id', 'ASC');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
